{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a4314967-0c0e-4a0e-ba41-c818b5c7477d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/allenleung/.zshenv:.:1: no such file or directory: /Users/allenleung/.cargo/env\n",
      "Requirement already satisfied: streamlit in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (1.63.0)\n",
      "Requirement already satisfied: requests in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (2.34.2)\n",
      "Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (4.15.0)\n",
      "Requirement already satisfied: geopy in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (2.5.0)\n",
      "Requirement already satisfied: folium in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (0.20.0)\n",
      "Requirement already satisfied: streamlit-folium in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (0.27.4)\n",
      "Requirement already satisfied: pandas in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (3.0.5)\n",
      "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (6.2.2)\n",
      "Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (8.5.0)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (2.5.1)\n",
      "Requirement already satisfied: packaging>=20 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (26.2)\n",
      "Requirement already satisfied: pillow<13,>=7.1.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (12.3.0)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (0.9.3)\n",
      "Requirement already satisfied: protobuf<8,>=5.26.1 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (7.36.1)\n",
      "Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (25.0.1)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.10.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (4.16.0)\n",
      "Requirement already satisfied: starlette<2,>=0.46.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (1.6.0)\n",
      "Requirement already satisfied: uvicorn<1,>=0.30.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (0.52.4)\n",
      "Requirement already satisfied: httptools<1,>=0.6.3 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: anyio<5,>=4.0.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (4.12.1)\n",
      "Requirement already satisfied: python-multipart<1,>=0.0.10 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (0.0.32)\n",
      "Requirement already satisfied: websockets<17,>=12.0.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (16.1.1)\n",
      "Requirement already satisfied: itsdangerous<3,>=2.1.2 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from streamlit) (2.2.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from requests) (3.4.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from requests) (3.18)\n",
      "Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from requests) (2.7.0)\n",
      "Requirement already satisfied: certifi>=2023.5.7 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from requests) (2026.7.22)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: jinja2 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.25.1)\n",
      "Requirement already satisfied: narwhals>=2.4.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.23.0)\n",
      "Requirement already satisfied: h11>=0.8 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)\n",
      "Requirement already satisfied: soupsieve>=1.6.1 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from beautifulsoup4) (2.8.4)\n",
      "Requirement already satisfied: geographiclib<3,>=1.52 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from geopy) (2.1)\n",
      "Requirement already satisfied: branca>=0.6.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from folium) (0.8.2)\n",
      "Requirement already satisfied: xyzservices in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from folium) (2026.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.28.0)\n",
      "Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/anaconda-toolbox/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit requests beautifulsoup4 geopy folium streamlit-folium pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "16c50ce4-ebff-4f13-bc67-dd2799be5cff",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-09-05 15:11:23.520 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.531 No runtime found, using MemoryCacheStorageManager\n",
      "2026-09-05 15:11:23.532 No runtime found, using MemoryCacheStorageManager\n",
      "2026-09-05 15:11:23.533 No runtime found, using MemoryCacheStorageManager\n",
      "2026-09-05 15:11:23.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.536 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.536 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.536 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.538 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.541 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.542 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.542 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.542 Session state does not function when running a script without `streamlit run`\n",
      "2026-09-05 15:11:23.542 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:23.544 No runtime found, using MemoryCacheStorageManager\n",
      "2026-09-05 15:11:23.544 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:26.938 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:26.939 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:26.939 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:26.944 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:26.945 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-05 15:11:26.945 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "from geopy.distance import geodesic\n",
    "from geopy.geocoders import Nominatim\n",
    "import folium\n",
    "from streamlit_folium import st_folium\n",
    "import time\n",
    "\n",
    "# -----------------------------------------------------------------------------\n",
    "# 頁面基本配置\n",
    "# -----------------------------------------------------------------------------\n",
    "st.set_page_config(page_title=\"灣仔京東Mall 實時租樓搜尋器\", layout=\"wide\")\n",
    "\n",
    "# 中心點：灣仔港灣道28號（灣景中心 / 京東Mall）\n",
    "CENTER_COORDS = (22.2803, 114.1762)\n",
    "CENTER_NAME = \"灣仔港灣道28號 (京東Mall)\"\n",
    "\n",
    "# 初始化地理編碼器 (用於取得地址經緯度)\n",
    "geolocator = Nominatim(user_agent=\"hk_property_finder_app_2026\")\n",
    "\n",
    "@st.cache_data(ttl=3600)  # 快取 1 小時，避免頻繁調用 API / 請求\n",
    "def get_coordinates(address_name):\n",
    "    \"\"\"取得地點經緯度，若定位失敗則傳回灣仔中心點周邊預設座標\"\"\"\n",
    "    try:\n",
    "        # 加上 \"Wan Chai, Hong Kong\" 提高精準度\n",
    "        search_query = f\"{address_name}, Wan Chai, Hong Kong\"\n",
    "        location = geolocator.geocode(search_query, timeout=5)\n",
    "        if location:\n",
    "            return location.latitude, location.longitude\n",
    "    except Exception:\n",
    "        pass\n",
    "    # 預設回傳灣仔約略座標\n",
    "    return 22.2780, 114.1740\n",
    "\n",
    "# -----------------------------------------------------------------------------\n",
    "# 實時數據抓取模組\n",
    "# -----------------------------------------------------------------------------\n",
    "@st.cache_data(ttl=1800)  # 快取 30 分鐘實時數據\n",
    "def fetch_centaline_rentals(min_price=15000, max_price=25000):\n",
    "    \"\"\"從中原 API 抓取灣仔區租樓實時數據\"\"\"\n",
    "    url = \"https://hk-api.centanet.com/centanetapi/api/Post/Search\"\n",
    "    headers = {\n",
    "        \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\",\n",
    "        \"Content-Type\": \"application/json\"\n",
    "    }\n",
    "    \n",
    "    # 搜尋條件: 租盤(PostType=Rent)、灣仔區\n",
    "    payload = {\n",
    "        \"postType\": \"Rent\",\n",
    "        \"displayText\": \"灣仔\",\n",
    "        \"minPrice\": min_price,\n",
    "        \"maxPrice\": max_price,\n",
    "        \"offset\": 0,\n",
    "        \"size\": 30,\n",
    "        \"lang\": \"zh-HK\"\n",
    "    }\n",
    "    \n",
    "    properties = []\n",
    "    try:\n",
    "        res = requests.post(url, json=payload, headers=headers, timeout=10)\n",
    "        if res.status_code == 200:\n",
    "            data = res.json()\n",
    "            items = data.get(\"data\", {}).get(\"list\", [])\n",
    "            for item in items:\n",
    "                title = item.get(\"title\") or item.get(\"estateName\", \"灣仔住宅\")\n",
    "                price = item.get(\"price\", 0)\n",
    "                size = f\"{item.get('saleableArea', 'N/A')} 呎\"\n",
    "                \n",
    "                # 取得經緯度 (中原 API 部份回傳包含 gpx/gpy，否則透過地址定位)\n",
    "                lat = item.get(\"gpx\")\n",
    "                lng = item.get(\"gpy\")\n",
    "                if not lat or not lng:\n",
    "                    lat, lng = get_coordinates(title)\n",
    "                \n",
    "                properties.append({\n",
    "                    \"title\": title,\n",
    "                    \"price\": int(price),\n",
    "                    \"size\": size,\n",
    "                    \"source\": \"中原地產\",\n",
    "                    \"lat\": float(lat),\n",
    "                    \"lng\": float(lng),\n",
    "                    \"url\": f\"https://hk.centanet.com/findproperty/detail/{item.get('id', '')}\"\n",
    "                })\n",
    "    except Exception as e:\n",
    "        st.error(f\"中原 API 抓取異常: {e}\")\n",
    "        \n",
    "    return properties\n",
    "\n",
    "\n",
    "@st.cache_data(ttl=1800)\n",
    "def fetch_28hse_rentals():\n",
    "    \"\"\"從 28Hse 網頁爬取灣仔區租樓數據\"\"\"\n",
    "    url = \"https://www.28hse.com/rent/residential/district-21\"  # district-21 為灣仔區\n",
    "    headers = {\n",
    "        \"User-Agent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36\"\n",
    "    }\n",
    "    \n",
    "    properties = []\n",
    "    try:\n",
    "        res = requests.get(url, headers=headers, timeout=10)\n",
    "        if res.status_code == 200:\n",
    "            soup = BeautifulSoup(res.text, \"html.parser\")\n",
    "            items = soup.find_all(\"div\", class_=\"property_item\") or soup.find_all(\"div\", class_=\"item\")\n",
    "            \n",
    "            for item in items[:15]:  # 取前 15 個\n",
    "                title_elem = item.find(\"a\", class_=\"title\") or item.find(\"h2\")\n",
    "                price_elem = item.find(\"span\", class_=\"price\") or item.find(\"div\", class_=\"price\")\n",
    "                \n",
    "                if title_elem and price_elem:\n",
    "                    title = title_elem.text.strip()\n",
    "                    price_str = price_elem.text.replace(\"$\", \"\").replace(\",\", \"\").strip()\n",
    "                    try:\n",
    "                        price = int(''.join(filter(str.isdigit, price_str)))\n",
    "                    except:\n",
    "                        continue\n",
    "                    \n",
    "                    lat, lng = get_coordinates(title)\n",
    "                    properties.append({\n",
    "                        \"title\": title,\n",
    "                        \"price\": price,\n",
    "                        \"size\": \"請參閱網頁\",\n",
    "                        \"source\": \"28Hse\",\n",
    "                        \"lat\": lat,\n",
    "                        \"lng\": lng,\n",
    "                        \"url\": \"https://www.28hse.com\" + title_elem.get(\"href\", \"\")\n",
    "                    })\n",
    "    except Exception as e:\n",
    "        st.warning(f\"28Hse 爬蟲抓取受限或超時: {e}\")\n",
    "        \n",
    "    return properties\n",
    "\n",
    "# -----------------------------------------------------------------------------\n",
    "# 主邏輯與 UI 介面\n",
    "# -----------------------------------------------------------------------------\n",
    "st.title(\"🏙️ 灣仔京東Mall 10分鐘步行圈 - 實時租樓搜尋器\")\n",
    "st.caption(\"數據來源：實時抓取中原地產 API 及 28Hse 數據\")\n",
    "\n",
    "# 側邊欄篩選\n",
    "st.sidebar.header(\"⚙️ 篩選條件\")\n",
    "price_range = st.sidebar.slider(\"預算範圍 (HKD)\", 10000, 35000, (16000, 24000), step=1000)\n",
    "max_walk_mins = st.sidebar.slider(\"最大步行時間 (分鐘)\", 1, 15, 10)\n",
    "data_source = st.sidebar.radio(\"數據來源選擇\", [\"中原地產 (實時 API)\", \"28Hse 網頁\", \"兩者混合\"])\n",
    "\n",
    "# 載入實時數據\n",
    "with st.spinner(\"正在連線抓取香港地產數據並計算步行時間...\"):\n",
    "    all_properties = []\n",
    "    if \"中原\" in data_source or \"混合\" in data_source:\n",
    "        all_properties.extend(fetch_centaline_rentals(min_price=price_range[0], max_price=price_range[1]))\n",
    "    if \"28Hse\" in data_source or \"混合\" in data_source:\n",
    "        all_properties.extend(fetch_28hse_rentals())\n",
    "\n",
    "# 計算距離與步行時間\n",
    "processed_data = []\n",
    "for p in all_properties:\n",
    "    dist_m = geodesic(CENTER_COORDS, (p['lat'], p['lng'])).meters\n",
    "    # 假設都市街道實際步行速度約 65 米/分鐘（考慮紅綠燈與過天橋時間）\n",
    "    walk_time = round(dist_m / 65)\n",
    "    \n",
    "    if price_range[0] <= p['price'] <= price_range[1] and walk_time <= max_walk_mins:\n",
    "        p['dist_m'] = round(dist_m)\n",
    "        p['walk_mins'] = walk_time\n",
    "        processed_data.append(p)\n",
    "\n",
    "df = pd.DataFrame(processed_data)\n",
    "\n",
    "# 介面渲染\n",
    "if not df.empty:\n",
    "    st.success(f\"已成功獲得 {len(df)} 個符合步行 {max_walk_mins} 分鐘內、租金 ${price_range[0]}-${price_range[1]} 的實時樓盤！\")\n",
    "    \n",
    "    col1, col2 = st.columns([3, 2])\n",
    "    \n",
    "    with col1:\n",
    "        st.subheader(\"🗺️ 樓盤位置地圖 (紅點為京東Mall)\")\n",
    "        m = folium.Map(location=CENTER_COORDS, zoom_start=16)\n",
    "        \n",
    "        # 中心點標記\n",
    "        folium.Marker(\n",
    "            CENTER_COORDS,\n",
    "            popup=CENTER_NAME,\n",
    "            icon=folium.Icon(color=\"red\", icon=\"shopping-cart\", prefix=\"fa\")\n",
    "        ).add_to(m)\n",
    "        \n",
    "        # 樓盤標記\n",
    "        for _, row in df.iterrows():\n",
    "            popup_html = f\"\"\"\n",
    "            <b>{row['title']}</b><br>\n",
    "            租金: HKD ${row['price']:,}/月<br>\n",
    "            步行時間: 約 <b>{row['walk_mins']}</b> 分鐘 ({row['dist_m']}米)<br>\n",
    "            來源: {row['source']}<br>\n",
    "            <a href=\"{row['url']}\" target=\"_blank\">查看原網站鏈接</a>\n",
    "            \"\"\"\n",
    "            folium.Marker(\n",
    "                [row['lat'], row['lng']],\n",
    "                popup=folium.Popup(popup_html, max_width=250),\n",
    "                icon=folium.Icon(color=\"blue\", icon=\"home\", prefix=\"fa\")\n",
    "            ).add_to(m)\n",
    "            \n",
    "        st_folium(m, width=700, height=520)\n",
    "\n",
    "    with col2:\n",
    "        st.subheader(\"📋 符合條件列表\")\n",
    "        display_df = df[['title', 'price', 'walk_mins', 'size', 'source', 'url']].copy()\n",
    "        display_df.columns = ['樓盤名稱', '月租 (HKD)', '步行(分)', '面積', '來源', '連結']\n",
    "        display_df = display_df.sort_values(by=['步行(分)', '月租 (HKD)'])\n",
    "        \n",
    "        st.dataframe(\n",
    "            display_df,\n",
    "            column_config={\n",
    "                \"連結\": st.column_config.LinkColumn(\"樓盤鏈接\", display_text=\"Go\")\n",
    "            },\n",
    "            use_container_width=True,\n",
    "            hide_index=True\n",
    "        )\n",
    "else:\n",
    "    st.warning(\"⚠️ 目前條件下未抓取到合適樓盤，建議擴大租金或步行時間範圍。\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
